name: todo
description: A Simple To do App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  sqflite: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/